esphome:
  name: geeni-powerstrip-2

bk72xx:
  board: cb3s

wifi:
  domain: .local
  networks:
  - ssid: !secret ssid
    password: !secret wifi_password

ota:
  - platform: esphome
    password: !secret ota_password

api:
 encryption:
   key: !secret api_key

logger:

text_sensor:
  - platform: libretiny
    version:
      name: LibreTiny Version

switch:
  - platform: gpio
    id: switch_1
    name: Relay 1
    pin: P6
    restore_mode: RESTORE_DEFAULT_OFF
  - platform: gpio
    id: switch_2
    name: Relay 2
    pin: P24
    restore_mode: RESTORE_DEFAULT_OFF
  - platform: gpio
    id: switch_3
    name: Relay 3
    pin: P26
    restore_mode: RESTORE_DEFAULT_OFF
  - platform: gpio
    id: switch_4
    name: Relay 4
    pin: P8
    restore_mode: RESTORE_DEFAULT_OFF
  - platform: gpio
    id: switch_5
    name: Relay 5
    pin: P7
    restore_mode: RESTORE_DEFAULT_OFF
  - platform: gpio
    id: switch_6
    name: Relay 6
    pin: P9
    restore_mode: RESTORE_DEFAULT_OFF

binary_sensor:
  - platform: gpio
    id: binary_switch_all
    pin:
      number: P23
      inverted: true
      mode: INPUT_PULLUP
    on_press:
      then:
        - switch.toggle: switch_1
        - switch.toggle: switch_2
        - switch.toggle: switch_3
        - switch.toggle: switch_4
        - switch.toggle: switch_5
        - switch.toggle: switch_6

status_led:
  pin:
    number: P14
    inverted: true
